---
title: "ABM Project"
author: "Bernard A. Coles IV"
date: "9/10/2019"
output: pdf_document
---

```{r Library, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(network)
library(devtools)
library(sna)
library(igraph)
library(tidyverse)
```

```{r Loading Data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
t1 <- as.matrix(read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/t1.dat", header = F, sep = " "))

t2 <- as.matrix(read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/t2.dat", header = F, sep = " "))

t3 <- as.matrix(read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/t3.dat", header = F, sep = " "))

t4 <- as.matrix(read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/t4.dat", header = F, sep = " "))

cov1 <- read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/cov1.dat", header = F, sep = " ", na.strings = "NA")

cov4 <- read.delim("~/desktop/Repository/Agent-Based-Models/Data/Marijtje-Signed-Longitudinal/cov4.dat", header = F, sep = " ", na.strings = "NA")

#Network Objects
#t1.net <- as.network(t1)
#t2.net <- as.network(t2)
#t3.net <- as.network(t3)
#t4.net <- as.network(t4)

#summary(t1.net)
#summary(t2.net)
#summary(t3.net)
#summary(t4.net)

```

```{r Cleaning, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#Matrices will contain -1, 0, or 1
#Time 1
for (i in 1:38) {
  for (j in 1:38) {
    t1[i,j] <- if_else(t1[i,j] == 1, 1,
                       if_else(t1[i,j] == 2, 1,
                               if_else(t1[i,j] == 3, 1,
                                       if_else(t1[i,j] == 4, 0, #Neutral relationships = 0? 
                                               if_else(t1[i,j] == 5, -1, 0)))))
  }
}
#Time 2
for (i in 1:38) {
  for (j in 1:38) {
    t2[i,j] <- if_else(t2[i,j] == 1, 1,
                       if_else(t2[i,j] == 2, 1,
                               if_else(t2[i,j] == 3, 1,
                                       if_else(t2[i,j] == 4, 0, #Neutral relationships = 0? 
                                               if_else(t2[i,j] == 5, -1, 0)))))
  }
}
#Time 3
for (i in 1:38) {
  for (j in 1:38) {
    t3[i,j] <- if_else(t3[i,j] == 1, 1,
                       if_else(t3[i,j] == 2, 1,
                               if_else(t3[i,j] == 3, 1,
                                       if_else(t3[i,j] == 4, 0, #Neutral relationships = 0? 
                                               if_else(t3[i,j] == 5, -1, 0)))))
  }
}
#Time 4
for (i in 1:38) {
  for (j in 1:38) {
    t4[i,j] <- if_else(t4[i,j] == 1, 1,
                       if_else(t4[i,j] == 2, 1,
                               if_else(t4[i,j] == 3, 1,
                                       if_else(t4[i,j] == 4, 0, #Neutral relationships = 0? 
                                               if_else(t4[i,j] == 5, -1, 0)))))
  }
}


```

```{r Visualize, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
op <- par(mfrow=c(2,2), mai = c(0,0,0.7,0))
set.seed(88)
gplot(t1.net, edge.col = "azure3", vertex.col="red3",label = seq(1,38), vertex.cex=1.5, label.pos = 5, label.cex=0.5)
title("Network (t1)")


gplot(t2.net, edge.col = "azure3", vertex.col="lightblue",label = seq(1,38), vertex.cex=1.5, label.pos = 5, label.cex=0.5)
title("Network (t2)")

gplot(t3.net, edge.col = "azure3", vertex.col="lavender",label = seq(1,38), vertex.cex=1.5, label.pos = 5, label.cex=0.5)
title("Network (t3)")

gplot(t4.net, edge.col = "azure3", vertex.col="darkgreen",label = seq(1,38), vertex.cex=1.5, label.pos = 5, label.cex=0.5)
title("Network (t3)")
par(op)
```

```{r Visualize Time1:4 }
op <- par(mfrow=c(2,2), mai = c(0,0,0.7,0))
#Making a Signed Graph Objects (Times 1:4)
t1.net <- graph_from_adjacency_matrix(t1, mode = "directed", weighted = T)
t2.net <- graph_from_adjacency_matrix(t2, mode = "directed", weighted = T)
t3.net <- graph_from_adjacency_matrix(t3, mode = "directed", weighted = T)
t4.net <- graph_from_adjacency_matrix(t4, mode = "directed", weighted = T)

#Time 1
E(t1.net)$color <- if_else( E(t1.net)$weight > 0, "green3", "red3")
V(t1.net)$label <- NA
V(t1.net)$size <- igraph::degree(t1.net, v = V(t1.net), mode = "in")*2
plot(t1.net, layout=layout_in_circle)
title("Time 1")

#Time 2
E(t2.net)$color <- if_else( E(t2.net)$weight > 0, "green3", "red3")
V(t2.net)$label <- NA
V(t2.net)$size <- igraph::degree(t2.net, v = V(t2.net), mode = "in")*2
plot(t2.net, layout=layout_in_circle)
title("Time 2")

#Time 3
E(t3.net)$color <- if_else( E(t3.net)$weight > 0, "green3", "red3")
V(t3.net)$label <- NA
V(t3.net)$size <- igraph::degree(t3.net, v = V(t3.net), mode = "in")*2
plot(t3.net, layout=layout_in_circle)
title("Time 3")

#Time 4
E(t4.net)$color <- if_else( E(t4.net)$weight > 0, "green3", "red3")
V(t4.net)$label <- NA
V(t4.net)$size <- igraph::degree(t4.net, v = V(t4.net), mode = "in")*2
plot(t4.net, layout=layout_in_circle)
title("time 4")
par(op)
```

#try to recode from the SAS code and produce some figures for a final paper (COmpare Fake data net with T4 Figure)

#Mix would be to identify the number of balanced verse unbalanced triads and then compare those 3 members 

```{r ABM}
#Simulated Positive and Negative Tie Data 
pos <- matrix(0, 38, 38)
neg <- matrix(0, 38, 38)

for (i in 1:38) {
  for (j in 1:38) {
    pos[i,j] <- rbinom(1, 1, .08)
  }
}

for (i in 1:38) {
  for (j in 1:38) {
    neg[i,j] <- rbinom(1, 1, .02)*-1
  }
}

#Imposing Symetry
p <- t(pos)
pos <- pos + p

n <- t(neg)
neg <- neg + n

network <- pos + neg
diag(network) <- 0

#Initial Network Visual
graph <- graph_from_adjacency_matrix(network, mode = "directed", weighted = T)

E(graph)$color <- if_else( E(graph)$weight > 0, "green3", "red3")
V(graph)$label <- NA
V(graph)$size <- igraph::degree(graph, v = V(graph), mode = "in")*2
plot1 <- plot(graph, layout=layout_with_fr)
```





















